//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordBete_s_Desktop_Cleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LordBete_s_Desktop_Cleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap browse_icon_dithered1 {
            get {
                object obj = ResourceManager.GetObject("browse_icon_dithered1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btn_backarrow {
            get {
                object obj = ResourceManager.GetObject("btn_backarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btn_close_sansserif {
            get {
                object obj = ResourceManager.GetObject("btn_close_sansserif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btn_minimise_sansserif {
            get {
                object obj = ResourceManager.GetObject("btn_minimise_sansserif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Btn_NewItem {
            get {
                object obj = ResourceManager.GetObject("Btn_NewItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Btn_Questionmark {
            get {
                object obj = ResourceManager.GetObject("Btn_Questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Btn_Questionmark1 {
            get {
                object obj = ResourceManager.GetObject("Btn_Questionmark1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btn_Settings {
            get {
                object obj = ResourceManager.GetObject("btn_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_thin_border {
            get {
                object obj = ResourceManager.GetObject("Button_thin_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DirectoryOrganiser_NewFilter {
            get {
                object obj = ResourceManager.GetObject("DirectoryOrganiser_NewFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DirectoryOrganiser_NewFilter1 {
            get {
                object obj = ResourceManager.GetObject("DirectoryOrganiser_NewFilter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DirectoryOrganiser_Settings_BG {
            get {
                object obj = ResourceManager.GetObject("DirectoryOrganiser_Settings_BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	[
        ///	  {
        ///      &quot;Name&quot;: &quot;Audio Files&quot;,
        ///	  &quot;DefaultLocation&quot;:&quot;\\Audio Files&quot;,
        ///	  &quot;FileTypes&quot;:[&quot;wav&quot;, &quot;mp3&quot;, &quot;ogg&quot;, &quot;asd&quot;, &quot;3gp&quot;, &quot;aac&quot;, &quot;aiff&quot;, &quot;flac&quot;, &quot;m4a&quot;, &quot;oga&quot;, &quot;wma&quot;],
        ///	  },
        ///
        ///	  {
        ///      &quot;Name&quot;: &quot;Images&quot;,
        ///      &quot;DefaultLocation&quot;:&quot;\\Pictures&quot;,
        ///	  &quot;FileTypes&quot;:[&quot;png&quot;, &quot;jpg&quot;, &quot;gif&quot;, &quot;psd&quot;, &quot;jfif&quot;, &quot;tif&quot;, &quot;bmp&quot;, &quot;img&quot;, &quot;jpeg&quot;, &quot;kra&quot;, &quot;svg&quot;, &quot;ai&quot;, &quot;ico&quot;]
        ///	  },
        ///	  
        ///	  {
        ///      &quot;Name&quot;: &quot;Fonts&quot;,
        ///      &quot;DefaultLocation&quot;:&quot;\\Fonts&quot;,
        ///      &quot;FileTypes&quot;:[&quot;otf&quot;, &quot;ttf&quot;, &quot;eot&quot;, &quot;woff&quot;, &quot;fnt&quot;, &quot;odttf&quot;, &quot;etx [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FileObjects_development {
            get {
                return ResourceManager.GetString("FileObjects_development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame_border_12 {
            get {
                object obj = ResourceManager.GetObject("frame_border_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frame_border_tape_09 {
            get {
                object obj = ResourceManager.GetObject("frame_border_tape_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MOSHED_2021_9_29_15_12_7_3 {
            get {
                object obj = ResourceManager.GetObject("MOSHED-2021-9-29-15-12-7-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_icon_win_98 {
            get {
                object obj = ResourceManager.GetObject("save_icon_win_98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Untitled_1 {
            get {
                object obj = ResourceManager.GetObject("Untitled-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
